### ISSUE TITLE
This is not an issue, I just have a question.

### ISSUE THREAD

**Issue by Evertt** [adib/MiniFlake#2]
Why did you choose to make the `starterNumber` in `InProcessFlakeMaker` random? Why not just count from 0 to `FlakeMaker.limitInstanceNumber`?

https://github.com/adib/MiniFlake/blob/8b3182365ca23766c34d1ced1568e2551eb2e53c/MiniFlake/Classes/FlakeMaker.swift#L150

### edit
Also, I almost never work with threads, so I barely know how they work, but isn't it true that threats can also be destroyed on the fly? Is it possible to subscribe to that event so that you can make the `instanceNumber` that that thread was using available again?

### edit2
Lastly, why isn't MiniFlake thread-safe? I just googled how to do that and it doesn't seem very complicated? Is it a design choice?

**Comment by adib** [comment]
Instance number allocations can be sequential, however de-allocations aren’t likely to be. Thus if instance numbers are allocated sequentially, there likely to be “holes” as they are de-allocated. Hence the allocation would need to scan for these holes every time, making it O(n)

Hence having a random number allocation would hopefully avoid the O(n) scanning for vacant slots. As long as there are plenty of those available.

Thanks
-- 
Sasmito Adibowo
https://basilsalad.com
